name: Teste Container
on:
  workflow_dispatch:
jobs:
  build-teste:
    runs-on: ubuntu-latest
    steps:
      - name: Execução do runner
        run: cat /etc/os-release
      - name: Execução no container
        uses: docker://alpine:latest
        with:
          entrypoint: cat
          args: /etc/os-release
